import NotAvailable from '../assets/svg/wi-na.svg'
import Sunny from '../assets/svg/wi-day-sunny.svg'
import LightClouds from '../assets/svg/wi-day-sunny-overcast.svg'
import PartlyCloudy from '../assets/svg/wi-day-cloudy.svg'
import Cloudy from '../assets/svg/wi-cloudy.svg'
import Rain from '../assets/svg/wi-rain.svg'
import RainMix from '../assets/svg/wi-rain-mix.svg'
import Snow from '../assets/svg/wi-snow.svg'
import RainShower from '../assets/svg/wi-day-rain.svg'
import SnowShower from '../assets/svg/wi-day-snow.svg'
import SleetShower from '../assets/svg/wi-day-sleet.svg'
import LightFog from '../assets/svg/wi-day-fog.svg'
import DenseFog from '../assets/svg/wi-fog.svg'
import FreezingRain from '../assets/svg/wi-sleet.svg'
import Thunderstorms from '../assets/svg/wi-thunderstorm.svg'
import Drizzle from '../assets/svg/wi-sprinkle.svg'
import Sandstorm from '../assets/svg/wi-sandstorm.svg'

export default { NotAvailable, Sunny, LightClouds, PartlyCloudy, Cloudy, Rain, RainMix, Snow, RainShower, SnowShower, SleetShower, LightFog , DenseFog, FreezingRain, Thunderstorms, Drizzle, Sandstorm }