"""empty message

Revision ID: 1bd6fc78b135
Revises: 7bfc98075d55
Create Date: 2023-09-13 19:11:03.974086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd6fc78b135'
down_revision = '7bfc98075d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cached_resource')
    # ### end Alembic commands ###
