"""empty message

Revision ID: 1fa934518941
Revises: ac955b50c960
Create Date: 2023-08-21 13:23:11.320964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fa934518941'
down_revision = 'ac955b50c960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked', sa.Text(), nullable=True))
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=10000),
               existing_nullable=True)
        batch_op.drop_column('checked')

    # ### end Alembic commands ###
