"""empty message

Revision ID: 4b0b07f5555a
Revises: 29ed48b77dec
Create Date: 2023-02-23 17:46:08.747742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b0b07f5555a'
down_revision = '29ed48b77dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=2000),
               type_=sa.String(length=10000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.String(length=10000),
               type_=mysql.VARCHAR(length=2000),
               existing_nullable=True)

    # ### end Alembic commands ###
