"""empty message

Revision ID: a8d6e6ae8866
Revises: 4b0b07f5555a
Create Date: 2023-02-27 14:36:50.332014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d6e6ae8866'
down_revision = '4b0b07f5555a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titleBgColor', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('contentBgColor', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('contentBgColor')
        batch_op.drop_column('titleBgColor')

    # ### end Alembic commands ###
