"""empty message

Revision ID: ac955b50c960
Revises: 3f4c2f082766
Create Date: 2023-06-01 19:09:04.458116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac955b50c960'
down_revision = '3f4c2f082766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('note', 'created_at', new_column_name='created_utc', existing_type=sa.DateTime())
    op.alter_column('note', 'updated_at', new_column_name='updated_utc', existing_type=sa.DateTime())
    op.alter_column('quote', 'created_at', new_column_name='created_utc', existing_type=sa.DateTime())
    op.alter_column('quote', 'updated_at', new_column_name='updated_utc', existing_type=sa.DateTime())

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('note', 'created_utc', new_column_name='created_at', existing_type=sa.DateTime())
    op.alter_column('note', 'updated_utc', new_column_name='updated_at', existing_type=sa.DateTime())
    op.alter_column('quote', 'created_utc', new_column_name='created_at', existing_type=sa.DateTime())
    op.alter_column('quote', 'updated_utc', new_column_name='updated_at', existing_type=sa.DateTime())

    # ### end Alembic commands ###
