"""empty message

Revision ID: dda7a8079295
Revises: 3f2e2c9c239d
Create Date: 2023-03-13 11:55:50.276991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dda7a8079295'
down_revision = '3f2e2c9c239d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(length=500), nullable=True))
        batch_op.drop_column('quote')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quote', mysql.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('text')

    # ### end Alembic commands ###
